site_name: Pi-Apps Docs
theme:
  name: material
  logo: 'https://github.com/Botspot/pi-apps/blob/master/icons/logo.png?raw=true'
  favicon: 'https://github.com/Botspot/pi-apps/blob/master/icons/logo.png?raw=true'
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

repo_name: Pi-Apps-Coders/docs
repo_url: https://github.com/Pi-Apps-Coders/docs
edit_uri: https://github.com/Pi-Apps-Coders/docs/edit/master/docs/
