name: Generate applist

on:
  schedule:
     - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  generate-applist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: generate
        run: |
          rm -rf ./pi-apps/
          git clone https://github.com/Botspot/pi-apps.git && cd pi-apps
          export version=$(bash -c 'git rev-parse HEAD | cut -c 1-8')
          cd ../ && rm -rf ./pi-apps/
          export current=$(cat appslist-commit.txt)
          [ "$current" == "$version" ] && exit 0
          git config user.name 'Ryan Fortner'
          git config user.email 'ryanfortner@users.noreply.github.com'
          git clone https://github.com/Botspot/pi-apps.wiki.git && cp ./pi-apps.wiki/Apps-List.md ./docs/apps-list.md && rm -rf pi-apps.wiki
          sed -i '1s/^/# Apps List\n/' ./docs/apps-list.md
          sed -i 's/blob/raw/' ./docs/apps-list.md
          sed -i 's/icon-64/icon-24/' ./docs/apps-list.md
          #replace $website to <website>
          for line in $(awk '/###/{getline; print}' ./docs/apps-list.md |  awk '{print $1;}' | grep http --color=none | sed 's/<br//g'); do 
            sed -i -z "s+$line+<$line>+" ./docs/apps-list.md
          done
          echo $version > appslist-commit.txt
          git add .
          git commit -m "[auto] update appslist"
          git push origin master
