name: Publish docs

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  publish-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: generate appslist
        run: |
          rm -rf ./pi-apps*/
          git config user.name 'Ryan Fortner'
          git config user.email 'ryanfortner@users.noreply.github.com'
          git clone https://github.com/Botspot/pi-apps.wiki.git
          export version=$(bash -c 'git rev-parse HEAD | cut -c 1-8')
          export current=$(cat appslist-commit.txt)
          [ "$current" == "$version" ] && exit 0
          rm -f ./docs/apps-list.md
          cat ./pi-apps.wiki/Apps-List.md >> ./docs/apps-list.md
          rm -rf ./pi-apps.wiki/
          sed -i 's/blob/raw/' ./docs/apps-list.md
          sed -i 's/icon-64/icon-24/' ./docs/apps-list.md
          sed -i 's/^# /## /' ./docs/apps-list.md
          #replace $website to <website>
          for line in $(awk '/###/{getline; print}' ./docs/apps-list.md |  awk '{print $1;}' | grep http --color=none | sed 's/<br//g'); do 
            sed -i -z "s+$line+<$line>+" ./docs/apps-list.md
          done
          echo $version > appslist-commit.txt
          git add .
          git commit -m "[auto] update appslist"
          git push origin master

      - name: deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: mkdocs.yml
          EXTRA_PACKAGES: build-base
